---
version: 3
images:
  base_image:
    name: quay.io/centos/centos:stream9
dependencies:
  python_interpreter:
    package_system: python3.12
    python_path: /usr/bin/python3.12
  ansible_core:
    package_pip: ansible-core>=2.18.0,<2.19.0
  ansible_runner:
    package_pip: ansible-runner
  galaxy: |
    collections:
      - name: ansible.snmp
      - name: community.general
      - name: community.sops
      - name: infoblox.nios_modules
      - name: netbox.netbox
  system: |
    cmake [platform:rpm compile]
    epel-release [platform:rpm]
    gcc [platform:rpm compile]
    gcc-c++ [platform:rpm compile]
    git-core [platform:rpm]
    git-lfs [platform:rpm]
    krb5-devel [platform:rpm compile]
    krb5-workstation [platform:rpm]
    libcurl-devel [platform:rpm compile]
    make [platform:rpm compile]
    net-snmp [platform:rpm compile]
    net-snmp-libs [platform:rpm compile]
    net-snmp-python [platform:rpm compile]
    net-snmp-utils [platform:rpm compile]
    openssl-devel [platform:rpm compile]
    podman-remote [platform:rpm]
    python3.12-devel [platform:rpm compile]
    rsync [platform:rpm]
    sshpass [platform:rpm]
    subversion [platform:dpkg]
    subversion [platform:rpm]
    unzip [platform:rpm]
    which [platform:rpm]
  python: |
    git+https://github.com/ansible/ansible-sign
    ansible-lint
    infoblox-client
    ncclient
    netaddr
    pandas
    paramiko
    pexpect>=4.5
    pykerberos
    PyMySQL
    pynetbox
    pyOpenSSL
    pypsrp[kerberos,credssp]
    python-daemon
    pywinrm[kerberos,credssp]
    pyyaml
    receptorctl
    six
    toml
additional_build_steps:
  append_final:
    - COPY --from=quay.io/getsops/sops:v3.11.0 /usr/local/bin/sops /usr/bin/sops
    - COPY --from=quay.io/ansible/receptor:devel /usr/bin/receptor /usr/bin/receptor
    - RUN mkdir -p /var/run/receptor
    - RUN git lfs install --system
    - RUN alternatives --install /usr/bin/python3 python3 /usr/bin/python3.12 312
    - RUN alternatives --install /usr/local/bin/pip pip /usr/local/bin/pip3.12 312
    - RUN alternatives --install /usr/bin/pydoc pydoc /usr/bin/pydoc3.12 312
    - RUN alternatives --install /usr/bin/python python /usr/bin/python3.12 312

...
